### ISSUE TITLE
Use as controlled component

### ISSUE THREAD

**Issue by mheiber** [mvader/react-categorized-tag-input#11]
TagInput acts like an [uncontrolled component](https://facebook.github.io/react/docs/forms.html#uncontrolled-components). That is, it maintains its own state, and the onChange callback just lets the listener know "hey, I changed."

We'd like to use it as a controlled component, so we can have more control over its state. Our immediate need is to dedupe tags, but I can see other uses as well.

The React convention is to have `value` be dynamic (like `input.value`) and `defaultValue` act like the `value` HTML attribute. This is how `input` works. That probably isn't an option for `TagInput` because it would break backwards compatibility.

I can PR for this, but would like your feedback on the best API design.
### Option 1
- If `value` never changes, treat it like `defaultValue`. If it changes, treat it like `React.Dom.input`'s `value` prop. This has the upside of more-closely following React conventions, but the downside of being potentially confusing.
### Option 2
- Add a `defaultValue` prop
- Setting `controlled={true}` makes the component a controlled component

**Comment by erizocosmico** [comment]
Hi, thanks for bringing up this issue.

Yes, it makes total sense to make it a controlled component, at the beginning it had a more complex value instead of a string and after tags became strings the component stayed the same but I'd be nice to change that.

This would be a new major release since it breaks backwards compatibility but I think implementing this is the right thing to do.

Tbh, I prefer the first option, treat the component as if it was an regular input, with its value and everything and not having much (not any because it needs to have some things like the panel closed and stuff) state of its own.

It would be just remove the value from the state and use it only as prop and then use `onChange` to give the owner the new tags. Then the owner would be in charge of updating the tags on its own. Since the value is now the owner's responsibility I think we should also remove the `transformTag` callback and just give those params to the `onChange` callback. What do you think?

**Comment by mheiber** [comment]
Good point about `transformTag` - I agree.
Regarding controlled vs. uncontrolled: it sounds like you're in favor of having the component always be controlled, rather than like `React.DOM.input`, which can be used either as a controlled component or an uncontrolled component. That would be fine, in my opinion, since it keeps things simple. Am I understanding correctly?

**Comment by erizocosmico** [comment]
Yes, I think we can include both ways and remove `transformTag` safely. If someone wants a more complicated use (like the functionality offered by `transformTag` right now) it can always be used in a managed way.

**Comment by mheiber** [comment]
Cool, thanks for your feedback.
I can do a PR for this:

> If value never changes, treat it like defaultValue. If it changes, treat it like React.Dom.input's value prop.  
> 
> remove `transformTag`

**Comment by erizocosmico** [comment]
Yes, perfect
